// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/kv_fabric.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ConsistencyMode maps 1:1 to store.ConsistencyMode.
// The numeric values are intentional — they match the iota order in engine.go
// so a cast is safe: store.ConsistencyMode(req.Consistency).
type ConsistencyMode int32

const (
	ConsistencyMode_STRONG           ConsistencyMode = 0
	ConsistencyMode_EVENTUAL         ConsistencyMode = 1
	ConsistencyMode_READ_YOUR_WRITES ConsistencyMode = 2
	ConsistencyMode_MONOTONIC        ConsistencyMode = 3
)

// Enum value maps for ConsistencyMode.
var (
	ConsistencyMode_name = map[int32]string{
		0: "STRONG",
		1: "EVENTUAL",
		2: "READ_YOUR_WRITES",
		3: "MONOTONIC",
	}
	ConsistencyMode_value = map[string]int32{
		"STRONG":           0,
		"EVENTUAL":         1,
		"READ_YOUR_WRITES": 2,
		"MONOTONIC":        3,
	}
)

func (x ConsistencyMode) Enum() *ConsistencyMode {
	p := new(ConsistencyMode)
	*p = x
	return p
}

func (x ConsistencyMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConsistencyMode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_kv_fabric_proto_enumTypes[0].Descriptor()
}

func (ConsistencyMode) Type() protoreflect.EnumType {
	return &file_proto_kv_fabric_proto_enumTypes[0]
}

func (x ConsistencyMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConsistencyMode.Descriptor instead.
func (ConsistencyMode) EnumDescriptor() ([]byte, []int) {
	return file_proto_kv_fabric_proto_rawDescGZIP(), []int{0}
}

type PutRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// CAS guard: only write if the key's current version == if_version.
	// 0 = unconditional write. Non-zero = optimistic concurrency control.
	IfVersion     uint64 `protobuf:"varint,3,opt,name=if_version,json=ifVersion,proto3" json:"if_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_proto_kv_fabric_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_fabric_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_proto_kv_fabric_proto_rawDescGZIP(), []int{0}
}

func (x *PutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PutRequest) GetIfVersion() uint64 {
	if x != nil {
		return x.IfVersion
	}
	return 0
}

type PutResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raft log index assigned to this write.
	// Use as MinVersion in subsequent monotonic reads, or pass to IssueToken for RYW.
	Version uint64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Non-empty when this node is not the leader.
	// Client should close this connection and dial redirect_to.
	RedirectTo string `protobuf:"bytes,2,opt,name=redirect_to,json=redirectTo,proto3" json:"redirect_to,omitempty"`
	// Ready-to-use RYW session token — base64-encoded JSON containing
	// the leader node ID and this write's version. Pass as session_token
	// in the next GetRequest to guarantee read-your-writes on any follower.
	SessionToken  string `protobuf:"bytes,3,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_proto_kv_fabric_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_fabric_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_proto_kv_fabric_proto_rawDescGZIP(), []int{1}
}

func (x *PutResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PutResponse) GetRedirectTo() string {
	if x != nil {
		return x.RedirectTo
	}
	return ""
}

func (x *PutResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type GetRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Key         string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Consistency ConsistencyMode        `protobuf:"varint,2,opt,name=consistency,proto3,enum=kvfabric.ConsistencyMode" json:"consistency,omitempty"`
	// RYW: opaque token from PutResponse.session_token.
	// The serving follower checks: appliedIndex >= token.WriteVersion.
	SessionToken string `protobuf:"bytes,3,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	// Monotonic: the client's current read watermark.
	// The serving follower checks: appliedIndex >= min_version.
	MinVersion    uint64 `protobuf:"varint,4,opt,name=min_version,json=minVersion,proto3" json:"min_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_kv_fabric_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_fabric_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_kv_fabric_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetRequest) GetConsistency() ConsistencyMode {
	if x != nil {
		return x.Consistency
	}
	return ConsistencyMode_STRONG
}

func (x *GetRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *GetRequest) GetMinVersion() uint64 {
	if x != nil {
		return x.MinVersion
	}
	return 0
}

type GetResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Value    []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`                       // nil if key does not exist
	Version  uint64                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`                  // MVCC version of the returned value
	IsStale  bool                   `protobuf:"varint,3,opt,name=is_stale,json=isStale,proto3" json:"is_stale,omitempty"`   // true when served from a follower that lags the leader
	LagMs    int64                  `protobuf:"varint,4,opt,name=lag_ms,json=lagMs,proto3" json:"lag_ms,omitempty"`         // estimated milliseconds behind the leader at read time
	FromNode string                 `protobuf:"bytes,5,opt,name=from_node,json=fromNode,proto3" json:"from_node,omitempty"` // which cluster node served this read
	// Non-empty when the follower cannot satisfy the consistency guarantee locally.
	// Client should retry at redirect_to (RYW / monotonic fallback to leader).
	RedirectTo    string `protobuf:"bytes,6,opt,name=redirect_to,json=redirectTo,proto3" json:"redirect_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_kv_fabric_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_fabric_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_kv_fabric_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetResponse) GetIsStale() bool {
	if x != nil {
		return x.IsStale
	}
	return false
}

func (x *GetResponse) GetLagMs() int64 {
	if x != nil {
		return x.LagMs
	}
	return 0
}

func (x *GetResponse) GetFromNode() string {
	if x != nil {
		return x.FromNode
	}
	return ""
}

func (x *GetResponse) GetRedirectTo() string {
	if x != nil {
		return x.RedirectTo
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	IfVersion     int64                  `protobuf:"varint,2,opt,name=if_version,json=ifVersion,proto3" json:"if_version,omitempty"` // 0 = unconditional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proto_kv_fabric_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_fabric_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_kv_fabric_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DeleteRequest) GetIfVersion() int64 {
	if x != nil {
		return x.IfVersion
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RedirectTo    string                 `protobuf:"bytes,1,opt,name=redirect_to,json=redirectTo,proto3" json:"redirect_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_kv_fabric_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_fabric_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_kv_fabric_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResponse) GetRedirectTo() string {
	if x != nil {
		return x.RedirectTo
	}
	return ""
}

type ScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         string                 `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           string                 `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_proto_kv_fabric_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_fabric_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_proto_kv_fabric_proto_rawDescGZIP(), []int{6}
}

func (x *ScanRequest) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *ScanRequest) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *ScanRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pairs         []*KVPair              `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	mi := &file_proto_kv_fabric_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_fabric_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_proto_kv_fabric_proto_rawDescGZIP(), []int{7}
}

func (x *ScanResponse) GetPairs() []*KVPair {
	if x != nil {
		return x.Pairs
	}
	return nil
}

type KVPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Version       uint64                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVPair) Reset() {
	*x = KVPair{}
	mi := &file_proto_kv_fabric_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVPair) ProtoMessage() {}

func (x *KVPair) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_fabric_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVPair.ProtoReflect.Descriptor instead.
func (*KVPair) Descriptor() ([]byte, []int) {
	return file_proto_kv_fabric_proto_rawDescGZIP(), []int{8}
}

func (x *KVPair) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KVPair) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *KVPair) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_kv_fabric_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_fabric_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_kv_fabric_proto_rawDescGZIP(), []int{9}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	IsLeader      bool                   `protobuf:"varint,2,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"`
	LeaderId      string                 `protobuf:"bytes,3,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	CommitIndex   uint64                 `protobuf:"varint,4,opt,name=commit_index,json=commitIndex,proto3" json:"commit_index,omitempty"`
	AppliedIndex  uint64                 `protobuf:"varint,5,opt,name=applied_index,json=appliedIndex,proto3" json:"applied_index,omitempty"`
	Followers     []*FollowerStatus      `protobuf:"bytes,6,rep,name=followers,proto3" json:"followers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_kv_fabric_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_fabric_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_kv_fabric_proto_rawDescGZIP(), []int{10}
}

func (x *StatusResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *StatusResponse) GetIsLeader() bool {
	if x != nil {
		return x.IsLeader
	}
	return false
}

func (x *StatusResponse) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *StatusResponse) GetCommitIndex() uint64 {
	if x != nil {
		return x.CommitIndex
	}
	return 0
}

func (x *StatusResponse) GetAppliedIndex() uint64 {
	if x != nil {
		return x.AppliedIndex
	}
	return 0
}

func (x *StatusResponse) GetFollowers() []*FollowerStatus {
	if x != nil {
		return x.Followers
	}
	return nil
}

type FollowerStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	MatchIndex    uint64                 `protobuf:"varint,2,opt,name=match_index,json=matchIndex,proto3" json:"match_index,omitempty"`
	LagEntries    int64                  `protobuf:"varint,3,opt,name=lag_entries,json=lagEntries,proto3" json:"lag_entries,omitempty"`
	LagMs         int64                  `protobuf:"varint,4,opt,name=lag_ms,json=lagMs,proto3" json:"lag_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowerStatus) Reset() {
	*x = FollowerStatus{}
	mi := &file_proto_kv_fabric_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowerStatus) ProtoMessage() {}

func (x *FollowerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_fabric_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowerStatus.ProtoReflect.Descriptor instead.
func (*FollowerStatus) Descriptor() ([]byte, []int) {
	return file_proto_kv_fabric_proto_rawDescGZIP(), []int{11}
}

func (x *FollowerStatus) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *FollowerStatus) GetMatchIndex() uint64 {
	if x != nil {
		return x.MatchIndex
	}
	return 0
}

func (x *FollowerStatus) GetLagEntries() int64 {
	if x != nil {
		return x.LagEntries
	}
	return 0
}

func (x *FollowerStatus) GetLagMs() int64 {
	if x != nil {
		return x.LagMs
	}
	return 0
}

var File_proto_kv_fabric_proto protoreflect.FileDescriptor

const file_proto_kv_fabric_proto_rawDesc = "" +
	"\n" +
	"\x15proto/kv_fabric.proto\x12\bkvfabric\"S\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1d\n" +
	"\n" +
	"if_version\x18\x03 \x01(\x04R\tifVersion\"m\n" +
	"\vPutResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12\x1f\n" +
	"\vredirect_to\x18\x02 \x01(\tR\n" +
	"redirectTo\x12#\n" +
	"\rsession_token\x18\x03 \x01(\tR\fsessionToken\"\xa1\x01\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12;\n" +
	"\vconsistency\x18\x02 \x01(\x0e2\x19.kvfabric.ConsistencyModeR\vconsistency\x12#\n" +
	"\rsession_token\x18\x03 \x01(\tR\fsessionToken\x12\x1f\n" +
	"\vmin_version\x18\x04 \x01(\x04R\n" +
	"minVersion\"\xad\x01\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\x12\x19\n" +
	"\bis_stale\x18\x03 \x01(\bR\aisStale\x12\x15\n" +
	"\x06lag_ms\x18\x04 \x01(\x03R\x05lagMs\x12\x1b\n" +
	"\tfrom_node\x18\x05 \x01(\tR\bfromNode\x12\x1f\n" +
	"\vredirect_to\x18\x06 \x01(\tR\n" +
	"redirectTo\"@\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1d\n" +
	"\n" +
	"if_version\x18\x02 \x01(\x03R\tifVersion\"1\n" +
	"\x0eDeleteResponse\x12\x1f\n" +
	"\vredirect_to\x18\x01 \x01(\tR\n" +
	"redirectTo\"K\n" +
	"\vScanRequest\x12\x14\n" +
	"\x05start\x18\x01 \x01(\tR\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\tR\x03end\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"6\n" +
	"\fScanResponse\x12&\n" +
	"\x05pairs\x18\x01 \x03(\v2\x10.kvfabric.KVPairR\x05pairs\"J\n" +
	"\x06KVPair\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x04R\aversion\"\x0f\n" +
	"\rStatusRequest\"\xe3\x01\n" +
	"\x0eStatusResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tis_leader\x18\x02 \x01(\bR\bisLeader\x12\x1b\n" +
	"\tleader_id\x18\x03 \x01(\tR\bleaderId\x12!\n" +
	"\fcommit_index\x18\x04 \x01(\x04R\vcommitIndex\x12#\n" +
	"\rapplied_index\x18\x05 \x01(\x04R\fappliedIndex\x126\n" +
	"\tfollowers\x18\x06 \x03(\v2\x18.kvfabric.FollowerStatusR\tfollowers\"\x82\x01\n" +
	"\x0eFollowerStatus\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vmatch_index\x18\x02 \x01(\x04R\n" +
	"matchIndex\x12\x1f\n" +
	"\vlag_entries\x18\x03 \x01(\x03R\n" +
	"lagEntries\x12\x15\n" +
	"\x06lag_ms\x18\x04 \x01(\x03R\x05lagMs*P\n" +
	"\x0fConsistencyMode\x12\n" +
	"\n" +
	"\x06STRONG\x10\x00\x12\f\n" +
	"\bEVENTUAL\x10\x01\x12\x14\n" +
	"\x10READ_YOUR_WRITES\x10\x02\x12\r\n" +
	"\tMONOTONIC\x10\x032\xa3\x02\n" +
	"\bKVFabric\x122\n" +
	"\x03Put\x12\x14.kvfabric.PutRequest\x1a\x15.kvfabric.PutResponse\x122\n" +
	"\x03Get\x12\x14.kvfabric.GetRequest\x1a\x15.kvfabric.GetResponse\x12;\n" +
	"\x06Delete\x12\x17.kvfabric.DeleteRequest\x1a\x18.kvfabric.DeleteResponse\x125\n" +
	"\x04Scan\x12\x15.kvfabric.ScanRequest\x1a\x16.kvfabric.ScanResponse\x12;\n" +
	"\x06Status\x12\x17.kvfabric.StatusRequest\x1a\x18.kvfabric.StatusResponseB%Z#github.com/ani03sha/kv-fabric/protob\x06proto3"

var (
	file_proto_kv_fabric_proto_rawDescOnce sync.Once
	file_proto_kv_fabric_proto_rawDescData []byte
)

func file_proto_kv_fabric_proto_rawDescGZIP() []byte {
	file_proto_kv_fabric_proto_rawDescOnce.Do(func() {
		file_proto_kv_fabric_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_kv_fabric_proto_rawDesc), len(file_proto_kv_fabric_proto_rawDesc)))
	})
	return file_proto_kv_fabric_proto_rawDescData
}

var file_proto_kv_fabric_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_kv_fabric_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_kv_fabric_proto_goTypes = []any{
	(ConsistencyMode)(0),   // 0: kvfabric.ConsistencyMode
	(*PutRequest)(nil),     // 1: kvfabric.PutRequest
	(*PutResponse)(nil),    // 2: kvfabric.PutResponse
	(*GetRequest)(nil),     // 3: kvfabric.GetRequest
	(*GetResponse)(nil),    // 4: kvfabric.GetResponse
	(*DeleteRequest)(nil),  // 5: kvfabric.DeleteRequest
	(*DeleteResponse)(nil), // 6: kvfabric.DeleteResponse
	(*ScanRequest)(nil),    // 7: kvfabric.ScanRequest
	(*ScanResponse)(nil),   // 8: kvfabric.ScanResponse
	(*KVPair)(nil),         // 9: kvfabric.KVPair
	(*StatusRequest)(nil),  // 10: kvfabric.StatusRequest
	(*StatusResponse)(nil), // 11: kvfabric.StatusResponse
	(*FollowerStatus)(nil), // 12: kvfabric.FollowerStatus
}
var file_proto_kv_fabric_proto_depIdxs = []int32{
	0,  // 0: kvfabric.GetRequest.consistency:type_name -> kvfabric.ConsistencyMode
	9,  // 1: kvfabric.ScanResponse.pairs:type_name -> kvfabric.KVPair
	12, // 2: kvfabric.StatusResponse.followers:type_name -> kvfabric.FollowerStatus
	1,  // 3: kvfabric.KVFabric.Put:input_type -> kvfabric.PutRequest
	3,  // 4: kvfabric.KVFabric.Get:input_type -> kvfabric.GetRequest
	5,  // 5: kvfabric.KVFabric.Delete:input_type -> kvfabric.DeleteRequest
	7,  // 6: kvfabric.KVFabric.Scan:input_type -> kvfabric.ScanRequest
	10, // 7: kvfabric.KVFabric.Status:input_type -> kvfabric.StatusRequest
	2,  // 8: kvfabric.KVFabric.Put:output_type -> kvfabric.PutResponse
	4,  // 9: kvfabric.KVFabric.Get:output_type -> kvfabric.GetResponse
	6,  // 10: kvfabric.KVFabric.Delete:output_type -> kvfabric.DeleteResponse
	8,  // 11: kvfabric.KVFabric.Scan:output_type -> kvfabric.ScanResponse
	11, // 12: kvfabric.KVFabric.Status:output_type -> kvfabric.StatusResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_kv_fabric_proto_init() }
func file_proto_kv_fabric_proto_init() {
	if File_proto_kv_fabric_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_kv_fabric_proto_rawDesc), len(file_proto_kv_fabric_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_kv_fabric_proto_goTypes,
		DependencyIndexes: file_proto_kv_fabric_proto_depIdxs,
		EnumInfos:         file_proto_kv_fabric_proto_enumTypes,
		MessageInfos:      file_proto_kv_fabric_proto_msgTypes,
	}.Build()
	File_proto_kv_fabric_proto = out.File
	file_proto_kv_fabric_proto_goTypes = nil
	file_proto_kv_fabric_proto_depIdxs = nil
}
